name: paysense
description: "PaySense - AI Powered Personal Finance App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Fonts
  google_fonts: ^6.3.1

  # Charts
  fl_chart: ^1.1.1

  # Animations
  flutter_animate: ^4.5.2

  # Permissions
  permission_handler: ^12.0.1

  # Date Formatting
  intl: ^0.20.2

  # UUID Generator
  uuid: ^4.5.1
  
  # Local storage (Hive)
  hive:
  hive_flutter:
  path_provider:
  flutter_local_notifications: ^22.2.0
  timezone: ^0.11.1
  crypto: ^3.0.7
  local_auth: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^5.13.0
  flutter_lints: ^6.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/