import 'package:flutter/material.dart';

import '../../core/routes/app_routes.dart';
import '../models/entitlement.dart';
import '../models/feature_search_item.dart';

/// FEATURE SEARCH — the single source of truth for what's searchable.
/// Every entry below points at a route this app actually registers in
/// `AppRouter` — this file is a curated INDEX of real features, never a
/// place to invent one. When a new screen/route is added to the app,
/// add one entry here to make it discoverable; nothing here should ever
/// reference a route that doesn't exist.
const List<FeatureSearchItem> kFeatureRegistry = [
  FeatureSearchItem(
    title: 'Tax Planner',
    subtitle: 'Plan and optimize your India income tax',
    keywords: ['tax', 'income tax', '80c', 'deduction', 'tax saving', 'regime'],
    category: 'Planning',
    icon: Icons.receipt_long_rounded,
    route: AppRoutes.taxPlanner,
    entitlement: Entitlement.taxPlanner,
  ),
  FeatureSearchItem(
    title: 'Loans',
    subtitle: 'Track EMIs and outstanding loan balances',
    keywords: ['loan', 'emi', 'debt', 'borrow', 'interest'],
    category: 'Money',
    icon: Icons.account_balance_rounded,
    route: AppRoutes.loans,
  ),
  FeatureSearchItem(
    title: 'Connect Bank',
    subtitle: 'Securely connect your financial accounts',
    keywords: ['bank', 'connect', 'account aggregator', 'aa', 'link account', 'sync bank'],
    category: 'Accounts',
    icon: Icons.account_balance_wallet_rounded,
    route: AppRoutes.bankConnect,
  ),
  FeatureSearchItem(
    title: 'Connected Financial Accounts',
    subtitle: 'Manage bank connections, sync, and consent',
    keywords: ['bank', 'connected accounts', 'sync', 'consent', 'revoke'],
    category: 'Accounts',
    icon: Icons.link_rounded,
    route: AppRoutes.connectedAccounts,
  ),
  FeatureSearchItem(
    title: 'Budgets',
    subtitle: 'Set spending limits by category',
    keywords: ['budget', 'spending limit', 'category'],
    category: 'Money',
    icon: Icons.pie_chart_rounded,
    route: AppRoutes.budget,
  ),
  FeatureSearchItem(
    title: 'Goals',
    subtitle: 'Save toward what matters to you',
    keywords: ['goal', 'saving', 'target'],
    category: 'Money',
    icon: Icons.flag_rounded,
    route: AppRoutes.goals,
  ),
  FeatureSearchItem(
    title: 'Financial Health',
    subtitle: 'Your overall financial health score',
    keywords: ['health', 'score', 'financial health'],
    category: 'Insights',
    icon: Icons.favorite_rounded,
    route: AppRoutes.financialHealth,
  ),
  FeatureSearchItem(
    title: 'Financial Health Trends',
    subtitle: 'How your financial health has changed over time',
    keywords: ['health trend', 'trajectory', 'improving', 'declining'],
    category: 'Insights',
    icon: Icons.show_chart_rounded,
    route: AppRoutes.financialHealthTrends,
  ),
  FeatureSearchItem(
    title: 'Compare Periods',
    subtitle: 'Compare this month against last month',
    keywords: ['compare', 'this month vs last month', 'period comparison'],
    category: 'Insights',
    icon: Icons.compare_arrows_rounded,
    route: AppRoutes.financialCompare,
    entitlement: Entitlement.comparePeriods,
  ),
  FeatureSearchItem(
    title: 'What-If Intelligence',
    subtitle: 'Ask "what if I..." and see the projected impact',
    keywords: ['what if', 'scenario', 'projection', 'simulate'],
    category: 'Insights',
    icon: Icons.psychology_alt_rounded,
    route: AppRoutes.aiCoach,
    entitlement: Entitlement.whatIf,
  ),
  FeatureSearchItem(
    title: 'Can I Afford This?',
    subtitle: 'Check whether a purchase fits your budget',
    keywords: ['afford', 'can i afford', 'purchase', 'buy'],
    category: 'Insights',
    icon: Icons.shopping_bag_rounded,
    route: AppRoutes.affordability,
  ),
  FeatureSearchItem(
    title: 'Financial Timeline',
    subtitle: 'A chronological view of your financial events',
    keywords: ['timeline', 'history', 'events'],
    category: 'Insights',
    icon: Icons.timeline_rounded,
    route: AppRoutes.financialTimeline,
    entitlement: Entitlement.financialTimeline,
  ),
  FeatureSearchItem(
    title: 'Financial Planning',
    subtitle: 'Long-term savings and debt projections',
    keywords: ['planning', 'emi', 'savings rate', 'projection'],
    category: 'Planning',
    icon: Icons.insights_rounded,
    route: AppRoutes.financialPlanning,
    entitlement: Entitlement.financialPlanning,
  ),
  FeatureSearchItem(
    title: 'Import Bank Statement',
    subtitle: 'Import transactions from a CSV bank statement',
    keywords: ['csv', 'import', 'bank statement', 'upload'],
    category: 'Accounts',
    icon: Icons.upload_file_rounded,
    route: AppRoutes.csvImport,
  ),
  FeatureSearchItem(
    title: 'AI Assistant',
    subtitle: 'Ask questions about your finances',
    keywords: ['ai', 'assistant', 'chat', 'ask'],
    category: 'Insights',
    icon: Icons.auto_awesome_rounded,
    route: AppRoutes.aiCoach,
    entitlement: Entitlement.aiAssistant,
  ),
  FeatureSearchItem(
    title: 'Recurring Money',
    subtitle: 'Subscriptions, bills, and EMIs in one place',
    keywords: ['recurring', 'subscription', 'netflix', 'spotify', 'emi', 'bills'],
    category: 'Money',
    icon: Icons.autorenew_rounded,
    route: AppRoutes.recurringMoney,
  ),
  FeatureSearchItem(
    title: 'Recurring Payments',
    subtitle: 'Schedule and manage recurring transactions',
    keywords: ['recurring transaction', 'schedule', 'automate'],
    category: 'Money',
    icon: Icons.event_repeat_rounded,
    route: AppRoutes.recurring,
  ),
  FeatureSearchItem(
    title: 'Bills',
    subtitle: 'Upcoming and overdue bills',
    keywords: ['bill', 'due', 'overdue', 'electricity', 'rent'],
    category: 'Money',
    icon: Icons.receipt_rounded,
    route: AppRoutes.bills,
  ),
  FeatureSearchItem(
    title: 'Export My Data',
    subtitle: 'Export your financial data as CSV or JSON',
    keywords: ['export', 'backup', 'download', 'csv', 'json', 'data'],
    category: 'Settings',
    icon: Icons.file_download_rounded,
    route: AppRoutes.dataExport,
  ),
  FeatureSearchItem(
    title: 'Reports',
    subtitle: 'Spending breakdown by category',
    keywords: ['report', 'breakdown', 'category spending'],
    category: 'Insights',
    icon: Icons.bar_chart_rounded,
    route: AppRoutes.reports,
  ),
  FeatureSearchItem(
    title: 'Transactions',
    subtitle: 'All your income and expenses',
    keywords: ['transaction', 'expense', 'income', 'history'],
    category: 'Money',
    icon: Icons.list_alt_rounded,
    route: AppRoutes.transactions,
  ),
  FeatureSearchItem(
    title: 'Wallets',
    subtitle: 'Your bank accounts and cash wallets',
    keywords: ['wallet', 'account', 'balance', 'cash'],
    category: 'Money',
    icon: Icons.account_balance_wallet_outlined,
    route: AppRoutes.wallet,
  ),
  FeatureSearchItem(
    title: 'Safe to Spend',
    subtitle: 'How much you can safely spend today',
    keywords: ['safe to spend', 'discretionary'],
    category: 'Insights',
    icon: Icons.savings_rounded,
    route: AppRoutes.safeToSpend,
  ),
  FeatureSearchItem(
    title: 'Cash Flow',
    subtitle: 'Your income and expense flow over time',
    keywords: ['cash flow', 'inflow', 'outflow'],
    category: 'Insights',
    icon: Icons.waterfall_chart_rounded,
    route: AppRoutes.cashFlow,
  ),
  FeatureSearchItem(
    title: 'Subscriptions',
    subtitle: 'Your active recurring subscriptions',
    keywords: ['subscription', 'netflix', 'spotify', 'renewal'],
    category: 'Money',
    icon: Icons.subscriptions_rounded,
    route: AppRoutes.subscriptions,
  ),
  FeatureSearchItem(
    title: 'Settings',
    subtitle: 'App preferences, security, and data',
    keywords: ['settings', 'preferences', 'security', 'currency', 'theme'],
    category: 'Settings',
    icon: Icons.settings_rounded,
    route: AppRoutes.settings,
  ),
];
